images_root_train: ../data/pyro-sdis/images
images_root_val: ../data/pyro-sdis/images
images_root_test: ../data/pyro-sdis/images
train_json: ../XAI-wildfire-smoke-detection/data/pyro-sdis/splits/train.json
val_json: ../XAI-wildfire-smoke-detection/data/pyro-sdis/splits/val.json
test_json: ../XAI-wildfire-smoke-detection/data/pyro-sdis/splits/test.json
job_id: 11
model_type: rcnn
model_family: resnet
model_size: 50
model_variant: fpn_v2
weight_sampling: dynamic
use_aug: true
aug_profile: standard
optimizer: SGD
lr0: 0.00125
momentum: 0.9
weight_decay: 0.0001
scheduler: plateau
warmup_epochs: 5
epochs: 50
patience: 6
batch: 4
num_workers: 8
data: data/pyro-sdis/splits/data.yaml
eval_iou: 0.45
eval_conf: 0.05
project: results/batch_runs/core
name: rcnn_aug_ws_dynamic_lr000125_seed_22
seed: 22
label_smoothing: 0.1
